version: '3.8'
services:
  frontend:
    build: ./app_react
    ports:
      - "3000:3000"
    depends_on:
      - backend
    links:
      - backend
    env_file:
      - ./app_react/.env

  backend:
    container_name: backend
    env_file:
      - ./app_flask/.env
    build: ./app_flask
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:80"
    depends_on:
      - backend

